# Generated by Django 2.2 on 2020-02-08 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(choices=[('Kathmandu', 'Kathmandu'), ('Pokhara', 'Pokhara'), ('Chitwan', 'Chitwan')], max_length=255),
        ),
        migrations.AlterField(
            model_name='profile',
            name='theme',
            field=models.CharField(choices=[('adventure', 'adventure'), ('nature', 'nature'), ('culture', 'culture'), ('food', 'food'), ('entertainment', 'entertainment'), ('leisure', 'leisure')], max_length=255),
        ),
    ]
